name: Deploy PHP 8.2 Latest

on:
  push:
    branches:
      - master  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: php82-fpm-wpcli-composer

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./php82-fpm-wpcli-composer  # Specify the folder
          push: true
          tags: criticalmasslatam/cm-wp-php:latest

      - name: Log out from Docker Hub
        run: docker logout
